### PR TITLE
Improved for node code gen

### PR DESCRIPTION
**Pull request by mirakst**
Up to/down to determines if <= or >= should be emitted.
Emits + in update if it is not a uminusnode.

### CODE REVIEW

**Review by damniko — CHANGES_REQUESTED** [review]
fix tests!

**Review by Sarmisuper — APPROVED** [review]
lgtm

**Comment by mirakst** [comment]
@damniko tests are fixed - changing uminus formatting is no bueno!
e.g. 5 * -2 would change to 5 * - 2 (hard to read!)

**Review by damniko — APPROVED** [review]
nom nom

**Pull request merged**
