### PR TITLE
Feature/antlr

### PR DESCRIPTION
**Pull request by KarmaKamikaze**

### CODE REVIEW

**Comment by KarmaKamikaze** [comment]
[Rewrite grammar to ANTLR format and yeet SableCC](https://trello.com/c/7xju8489/73-rewrite-grammar-to-antlr-format-and-yeet-sablecc)

**Review by Sarmisuper — APPROVED** [review]
https://gfycat.com/flakymerryiberianchiffchaff

**Review by selectionator — APPROVED** [review]
LGTM super nice 👍

**Review by WassawRoki — APPROVED** [review]
I Like it, det nemt at læse igennem :D 👍

**Review by Sarmisuper — APPROVED** [review]
image

**Comment by KarmaKamikaze** [comment]
[Extend the listener to implement (yet another) pretty printer](https://trello.com/c/bcj2V6ah/74-extend-the-listener-to-implement-yet-another-pretty-printer)

**Pull request merged**
